[package]
name = "pineapple-pen"
version = "0.1.0"
authors = ["Leonardo F. <leonardofe@pm.me>"]
edition = "2018"


[dependencies]
gtk = { version = "0.9.0", features = ["v3_16"] }
gio = { version = "", features = ["v2_44"] }
glib = ""
log = "0.4"
env_logger = "0.7.1"
cairo-rs = "0.9.1"
